'use strict';
// SAMPLE DATA ONLY. Builds fixtures/demo.json: weekly columns generated by the engine, with a few
// deliberate differences in the "n8n" columns so the dashboard layout can be seen. Says nothing about real behaviour.
const fs = require('fs'), path = require('path');
const { parseCsv, toObjects, fromCsvTexts } = require('../src/curriculum');
const { createEngine } = require('../src/engine');
const fx = n => fs.readFileSync(path.join(__dirname, '..', 'fixtures', n), 'utf8');
const texts = { maths: fx('maths.csv'), english: fx('english.csv'), holidays: fx('holidays.csv') };
const engine = createEngine(fromCsvTexts(texts));
let seed = 7; const rnd = () => (seed = (seed * 1664525 + 1013904223) % 4294967296) / 4294967296;
const pick = a => a[Math.floor(rnd() * a.length)];
const M = ['JrBg', '0a', '0b', '1', '2', '3', '4', '5'], E = ['SrR', 'MrR', 'F1', 'G1', 'H1', 'I1', 'J1'];
const start = () => { const m = rnd() < .5, lv = pick(m ? M : E), ch = pick('ABCDEFGHIJKLMNOP'.split('')); return `${m ? 'M' : 'E'} ${lv} ${ch}\nPT`; };
const dates = ['08/18/2026', '08/25/2026', '09/01/2026', '09/08/2026', '09/15/2026', '09/22/2026', '09/29/2026'];
const N = 42, claude = [], n8n = [];
let cur = Array.from({ length: N }, start);
const cols = [cur];
for (let w = 1; w < dates.length; w++) {
  const gen = engine.generate(cur.map((t, i) => ({ student_name: 'x', last_week_log: t, is_present: true, book_collected: true, new_header_date: dates[w] }))).map(g => g.next_week_log);
  // what "n8n" wrote: same, with a handful of deliberate differences
  const written = gen.map((t, i) => {
    const r = rnd();
    if (r < .04) return t.replace(/ ([A-Z])(\n|$)/, (m, c, e) => ` ${String.fromCharCode(((c.charCodeAt(0) - 64) % 26) + 65)}${e}`);   // different chapter
    if (r < .09) return t.replace(/\nPT$/, ' 38/40\nPT');                                                                      // staff typed a score after
    if (r < .12) return t.replace(/\nPT$/, ' (MT1 NXT)\nPT');                                                                  // note in brackets
    return t;
  });
  cols.push(written); cur = written;
}
const rows = Array.from({ length: N }, (_, i) => ({ row: i + 4, cells: [{ text: `student ${i + 4}` }, ...cols.map(c => ({ text: c[i] }))] }));
const grid = { headerRow: ['Name', ...dates], rows };
fs.writeFileSync(path.join(__dirname, '..', 'fixtures', 'demo.json'), JSON.stringify({
  curriculum: { maths: toObjects(parseCsv(texts.maths)), english: toObjects(parseCsv(texts.english)), holidays: toObjects(parseCsv(texts.holidays)) },
  tabs: { 'Table1 2026': grid },
}));
console.log('wrote fixtures/demo.json');
